version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-muscu
    environment:
      MYSQL_ROOT_PASSWORD: muscu1234
      MYSQL_DATABASE: musculation_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - muscu-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-muscu
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - muscu-network
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  muscu-network: